### ISSUE TITLE
Cannot use SSH key

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/darsync#1]
Dear Darsync maintainer, hi Martin,

I think Darsync is great. However, when testing it, I got into trouble with the SSH key. The attached zipped video shows the problem :+1:

[darsync_problem.zip](https://github.com/UPPMAX/darsync/files/14191847/darsync_problem.zip)

Could you help me find out what I did wrong, and/or thank me for testing the script :-) ?

Thanks and cheers, Richel

**Comment by dahlo** [comment]
Resolved over zoom.
